[AccessTransformers]
; BlueprintCallable=(Class="/Script/FactoryGame.FGBuildGun", Function="GetHitResult")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGBuildGun", Property="mHitResult")
; Friend=(Class="UFGButtonHintBar", FriendClass="UButtonHintBarFix")
Friend=(Class="AFGChargedWeapon", FriendClass="UUEVREnhancements_VREquipment")
Friend=(Class="AFGWeapon", FriendClass="UUEVREnhancements_VREquipment")
Accessor = (Class="AFGWeapon", Property="mCurrentDispersion")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGOnboardingStep", Property="Objectives")
BlueprintReadWrite=(Class="/Script/FactoryGame.FGOnboardingStep", Property="Hints")
BlueprintCallable=(Class="/Script/FactoryGame.FGEquipment", Function="SetEquipmentVisibility")